# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uchicagonative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uchicagonative
    pod 'R.swift'
    pod 'SwiftFormat/CLI', '~> 0.44'
    pod 'Cartography', '~> 3.0'
    pod 'SwiftLint'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'SVGKit', '~> 3.0.0-beta3' 

end
