# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uchicagonative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uchicagonative
    pod 'R.swift'
    pod 'SwiftFormat/CLI', '~> 0.44'
    pod 'Cartography', '~> 3.0'
    pod 'SwiftLint'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'SVGKit', '~> 3.0.0-beta3' 
    pod 'KeyboardNotificationsObserver', '~> 0.2'
    pod 'Firebase/Database'

end

target 'uchicagonativeTests' do
 inherit! :search_paths
   # Pods for testing
     pod 'Firebase/Auth'
	
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
end